version: '3.8'

services:
  stremio-ai-companion:
    image: ghcr.io/willtho89/stremio-ai-companion:latest
    ports:
      - "8000:8000"
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-stremio-ai-companion-default-key}
      - UVICORN_WORKERS=${UVICORN_WORKERS:-0}
      - ENABLE_FEED_CATALOGS=${ENABLE_FEED_CATALOGS:-true}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://openrouter.ai/api/v1}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-openai/gpt-5-mini:online}
      - TMDB_API_KEY=${TMDB_API_KEY:-}
      - RPDB_API_KEY=${RPDB_API_KEY:-}

      # Optional: Proxy settings
      # Route all traffic through a SOCKS5h proxy (e.g. WARP container on port 1080)
      # Useful if server IPs are blocked by TMDB or API Providers.
      # Uncomment both lines below to enable:
      # - ALL_PROXY=socks5h://warp:1080
      # - NO_PROXY=localhost,127.0.0.1

    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped